services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    # Pre-seed script is required as a volume to load mock database
    # Data inside the container is lost on restart unless you persist it with a volume.
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    

  backend:
    build: ./backend/
    ports:
      - "8080:5000"
    environment: 
      DB_HOST: db
      DB_NAME: marksdb
      DB_USER: marksuser
      DB_PASSWORD: markspass


  frontend:
    build: ./frontend/
    ports:
      - "5000:80"

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug


volumes:
  db-data:
